name: Deploy Vite client to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Build client for Pages
        env:
          GITHUB_PAGES: "true"
        run: |
          npm run build
      
      - name: Add SPA routing support for GitHub Pages
        run: |
          # Copy the main index.html to 404.html for SPA fallback
          cp dist/public/index.html dist/public/404.html
          
          # Create additional SPA route files to help with direct access
          mkdir -p dist/public/cases
          mkdir -p dist/public/critical-cases
          mkdir -p dist/public/users
          mkdir -p dist/public/ai-models
          mkdir -p dist/public/audit-logs
          mkdir -p dist/public/monitoring
          mkdir -p dist/public/settings
          
          # Copy index.html to each route directory for better compatibility
          cp dist/public/index.html dist/public/cases/index.html
          cp dist/public/index.html dist/public/critical-cases/index.html
          cp dist/public/index.html dist/public/users/index.html
          cp dist/public/index.html dist/public/ai-models/index.html
          cp dist/public/index.html dist/public/audit-logs/index.html
          cp dist/public/index.html dist/public/monitoring/index.html
          cp dist/public/index.html dist/public/settings/index.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Vite outDir: dist/public
          path: dist/public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
